sudo: false

language: python
cache: pip
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7


before_install:
  - pip install -U pip
  - pip install -r test_requirements.txt

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=verifyreq
  - pylint verifyreq tests
  - flake8

after_script: coveralls
